=== NazarKhandoha/XMLDTD/Workers.dtd
<!ELEMENT Workers (Worker+)>
<!ELEMENT Worker (Category, Salary, Experience, Adress, (MobilePhone|HomePhone), Information?)>
<!ELEMENT Category (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Experience (#PCDATA)>
<!ELEMENT Adress (#PCDATA)>
<!ELEMENT MobilePhone (#PCDATA)>
<!ELEMENT HomePhone (#PCDATA)>
<!ELEMENT Information (#PCDATA)>

<!ATTLIST Worker ID ID #REQUIRED>
<!ATTLIST Worker Name CDATA #REQUIRED>
<!ATTLIST Worker Surname CDATA #REQUIRED>
<!ATTLIST Worker Age CDATA #REQUIRED>
<!ATTLIST Worker Sex CDATA #IMPLIED>

=== NazarKhandoha/XMLDTD/Workers.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Workers SYSTEM "C:\Users\Администратор\Documents\Visual Studio 2010\Projects\3 курс\Візуальне програмування\Lab6\Workers.dtd">
<Workers>
  <Worker ID="_1" Name="Bill" Surname="Newman" Age="22" Sex="M">
    <Category>Admin</Category>
    <Salary>1200</Salary>
    <Experience>1</Experience>
    <Adress>Burbon St. 12</Adress>
    <MobilePhone>093-23-45-218</MobilePhone>
  </Worker>
  <Worker ID="_2" Name="Kate" Surname="Nash" Age="34" Sex="F">
    <Category>Developer</Category>
    <Salary>3000</Salary>
    <Experience>6</Experience>
    <Adress>Burbon St.9</Adress>
    <HomePhone>235-74-24</HomePhone>
  </Worker>
</Workers>
